---
name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

permissions: {}

jobs:
  release:
    permissions:
      contents: write # Required to create the GitHub release.
    uses: glueckkanja/gkvm-tools/.github/workflows/release.yml@32dbc969db8c848270b2a13390da3132b79a0651 # v0.1.3
